### ISSUE TITLE
compiling without wcstools breaks make process

### ISSUE THREAD

**Issue by zguangyu** [RTS2/rts2#12]
When I configure rts2 without the --with-wcstools parameter, it says "You don't have wcstools installed. That will not affect compilation." during configuration. In fact it really affects the compilation. The libwcstools variable is set to yes by default, and the LIBWCS macro is set to true, which will cause the tpm.cpp being compiled. I need to explicitly add the --with-wcstools=no parameter to the configure script.

**Comment by pkubanek** [comment]
Fixed by latest commit as well.

**Comment by zguangyu** [comment]
Thank you for the fix!
